```yaml id="t7y4u1"
name: Test Workflow

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello GitHub Actions"
```
