name: Deploy Site

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Use staging robots.txt
        if: github.ref == 'refs/heads/develop'
        run: cp env/robots-stg.txt robots.txt

      - name: Use production robots.txt
        if: github.ref == 'refs/heads/main'
        run: cp env/robots-prod.txt robots.txt

      - name: Remove GTM tags for staging
        if: github.ref == 'refs/heads/develop'
        run: |
          sed -i 's|<!-- GTM_HEAD -->||' index.html
          sed -i 's|<!-- GTM_BODY -->||' index.html

      - name: Insert GTM tags for production
         if: github.ref == 'refs/heads/main'
        run: |
          GTM_HEAD=$(cat env/gtm-head-prod.html)
          GTM_BODY=$(cat env/gtm-body-prod.html)

          sed -i "s|<!-- GTM_HEAD -->|$GTM_HEAD|" index.html
          sed -i "s|<!-- GTM_BODY -->|$GTM_BODY|" index.html

      - name: Deploy to Staging S3
        if: github.ref == 'refs/heads/develop'
        run: aws s3 sync . s3://travel-site-stg-bucket-076589004675-ap-northeast-1-an --delete --exclude ".git/*" --exclude ".github/*" --exclude "sitemap.xml"

      - name: Clear Staging CloudFront Cache
        if: github.ref == 'refs/heads/develop'
        run: aws cloudfront create-invalidation --distribution-id EDW6HT216VI4D --paths "/*"

      - name: Deploy to Production S3
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync . s3://travel-site-tadac-bucket-076589004675-ap-northeast-1-an --delete --exclude ".git/*" --exclude ".github/*"

      - name: Clear Production CloudFront Cache
        if: github.ref == 'refs/heads/main'
        run: aws cloudfront create-invalidation --distribution-id E2244AII0JXCGP --paths "/*"

